image: gcc

stages:
  - build
  - test
  - release

variables:
  CMAKE_BUILD_TYPE: Debug

before_script:
  - apt-get update -qq && apt-get install -y cmake g++ lcov

build:
  stage: build
  script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
    - cmake --build build
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - cd build
    - ctest --output-on-failure
  dependencies:
    - build
  artifacts:
    paths:
      - build/

coverage:
  stage: test
  script:
    - cd build
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - lcov --list coverage.info
    - bash <(curl -s https://codecov.io/bash) -f coverage.info
  only:
    - master

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - tags
  needs:
    - build
    - test
  script:
    - echo "Creating release $CI_COMMIT_REF_NAME"
    - mkdir release
    - cp build/bin/* release/
    - cp build/lib/*.so release/
  artifacts:
    paths:
      - release/*
  release:
    name: $CI_COMMIT_TAG
    tag_name: 'Release $CI_COMMIT_TAG'
    description: $CI_COMMIT_TAG_DESCRIPTION
