stages:
  - build
  - test
  - release

variables:
  CMAKE_BUILD_TYPE: Debug

before_script:
  - apt-get update -qq && apt-get install -y cmake g++ lcov

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..
    - make

test:
  stage: test
  script:
    - cd build
    - ctest

coverage:
  stage: test
  script:
    - cd build
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - lcov --list coverage.info
    - bash <(curl -s https://codecov.io/bash) -f coverage.info
  only:
    - master

release:
  stage: release
  only:
    - tags
  script:
    - echo "Creating release $CI_COMMIT_REF_NAME"
    - mkdir release
    - cp build/bin/* release/
  artifacts:
    paths:
      - release/*
  release:
    name: $CI_COMMIT_REF_NAME
    tag_name: $CI_COMMIT_REF_NAME
    description: "Release for tag $CI_COMMIT_REF_NAME"
