image: gcc

stages:
  - build
  - test
  - release

variables:
  CMAKE_BUILD_TYPE: Debug

before_script:
  - apt-get update -qq && apt-get install -y cmake g++ lcov gcovr

build:
  stage: build
  script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
    - cmake --build build
  artifacts:
    paths:
      - build/

#https://docs.gitlab.com/ee/ci/testing/unit_test_report_examples.html
test:
  stage: test
  needs:
    - build
  script:
    - cd build/bin
    - for test_executable in test_*; do ./$test_executable --gtest_output="xml:report-${test_executable}.xml"; done
  artifacts:
    when: always
    reports:
      junit: test_results-*.xml

#https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html
coverage:
  stage: test
  needs:
    - build
  script:
    - cd build
    - ctest --output-on-failure
    - cd ..
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/coverage.xml

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - tags
  needs:
    - build
    - test
  script:
    - echo "Creating release $CI_COMMIT_REF_NAME"
    - mkdir -p release/lib
    - cp build/bin/* release/
    - rm relese/test_*
    - cp build/lib/*.so release/lib
    - mv build/coverage_report release
  artifacts:
    paths:
      - release/*
    expire_in: never
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: $CI_COMMIT_TAG_DESCRIPTION
    assets:
      links:
        - name: 'File from cat'
          url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID}/artifacts/release'