image: gcc

stages:
  - build
  - test
  - prepare
  - release

variables:
  CMAKE_BUILD_TYPE: Debug

before_script:
  - apt-get update -qq && apt-get install -y cmake g++ lcov gcovr

build:
  stage: build
  script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
    - cmake --build build
  artifacts:
    paths:
      - build/

#https://docs.gitlab.com/ee/ci/testing/unit_test_report_examples.html
test:
  stage: test
  needs:
    - build
  script:
    - cd build/bin
    - for test_executable in test_*; do ./$test_executable --gtest_output="xml:report-${test_executable}.xml"; done
  artifacts:
    when: always
    paths:
      - build/bin/*.xml
    reports:
      junit: build/bin/*.xml

#https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html
coverage:
  stage: test
  needs:
    - build
  script:
    - cd build
    - ctest --output-on-failure
    - cd ..
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    when: always
    paths:
      - build/coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/coverage.xml

pre-commit:
  stage: test
  image: python:3.10.2-slim-bullseye
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - apt update && apt install -y --no-install-recommends git
  script:
    - pre-commit run --from-ref origin/HEAD --to-ref HEAD

prepare_job:
  stage: prepare
  only:
    - tags
  needs:
    - build
    - test
  script:
    - echo "Creating release $CI_COMMIT_REF_NAME"
    - cmake -S . -B release -DCMAKE_BUILD_TYPE=Release
    - cmake --build release
    - rm -rf release/bin/test_*
    - mkdir -p $CI_COMMIT_TAG
    - cp release/bin/* $CI_COMMIT_TAG
    - cp -R release/lib/*.so $CI_COMMIT_TAG
    - echo "RELEASE_ART_JOB_ID=$CI_JOB_ID"
    - echo "RELEASE_ART_JOB_ID=$CI_JOB_ID" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env
    paths:
      - $CI_COMMIT_TAG/*
    expire_in: never

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_job
      artifacts: true
  only:
    - tags
  script:
    - echo "Running the release job"
  release:
    tag_name: $CI_COMMIT_TAG
    name: "Release $CI_COMMIT_TAG"
    description: "Release $CI_COMMIT_TAG"
    assets:
      links:
        - name: "Release $CI_COMMIT_TAG"
          url: "${CI_PROJECT_URL}/-/jobs/${RELEASE_ART_JOB_ID}/artifacts/download"
