repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: \.cmake$
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: [pyyaml]

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.5"
    hooks:
      - id: codespell
        args: ["-L", "ba"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v13.0.0"
    hooks:
      - id: clang-format

  - repo: https://github.com/pre-commit/mirrors-cpplint
    rev: v1.5
    hooks:
      - id: cpplint
        args: ['--filter=-build/include_what_you_use']
