if(EXISTS "/home/kali/repos/cmake-gtest-template/release/src/testsConsoleApp/test_main[1]_tests.cmake")
  include("/home/kali/repos/cmake-gtest-template/release/src/testsConsoleApp/test_main[1]_tests.cmake")
else()
  add_test(test_main_NOT_BUILT test_main_NOT_BUILT)
endif()
